import type { Event, EventCategory } from '@/types';

// Mock-Daten für Veranstaltungen
// In der Produktion könnten diese von verschiedenen Quellen kommen

export const MOCK_EVENTS: Event[] = [
  {
    id: '1',
    title: '650 Jahre Zernsdorf - Jubiläumsfest',
    slug: '650-jahre-zernsdorf-2025-07-18',
    description:
      'Großes Dorffest zum 650-jährigen Jubiläum von Zernsdorf mit Live-Musik, Ständen lokaler Vereine, Kinderprogramm und Feuerwerk. Ein Highlight für die ganze Familie!',
    description_en: null,
    location_name: 'Dorfaue Zernsdorf',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-07-18',
    start_time: '14:00',
    end_date: '2025-07-20',
    end_time: '22:00',
    is_all_day: false,
    category: 'festival',
    event_type: 'single',
    organizer_name: 'Bürgerhaus Zernsdorf',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: 'https://buergerhaus-zernsdorf.de',
    image_url: null,
    images: null,
    is_active: true,
    is_featured: true,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: false,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'Osterfeuer am Lankensee',
    slug: 'osterfeuer-lankensee-2025-04-19',
    description:
      'Traditionelles Osterfeuer am Strand des Lankensees. Für Getränke und Bratwurst ist gesorgt. Der Heimatverein freut sich auf zahlreiche Besucher.',
    description_en: null,
    location_name: 'Strand Lankensee',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-04-19',
    start_time: '18:00',
    end_date: null,
    end_time: null,
    is_all_day: false,
    category: 'community',
    event_type: 'single',
    organizer_name: 'Heimatverein Zernsdorf',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: null,
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: false,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Frühjahrsmarkt',
    slug: 'fruehjahrsmarkt-2025-05-10',
    description:
      'Regionaler Markt mit frischen Produkten von lokalen Bauern, Handwerkskunst und Pflanzen für den Garten.',
    description_en: null,
    location_name: 'Hauptstraße Zernsdorf',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-05-10',
    start_time: '09:00',
    end_date: '2025-05-10',
    end_time: '15:00',
    is_all_day: false,
    category: 'market',
    event_type: 'single',
    organizer_name: 'Gemeinde Königs Wusterhausen',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: null,
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: false,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '4',
    title: 'Konzert: Blasorchester Königs Wusterhausen',
    slug: 'konzert-blasorchester-2025-06-21',
    description:
      'Sommerkonzert des Blasorchesters mit klassischen und modernen Stücken. Eintritt frei, Spenden willkommen.',
    description_en: null,
    location_name: 'Bürgerhaus Zernsdorf',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-06-21',
    start_time: '19:00',
    end_date: null,
    end_time: null,
    is_all_day: false,
    category: 'culture',
    event_type: 'single',
    organizer_name: 'Blasorchester Königs Wusterhausen',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: 'https://buergerhaus-zernsdorf.de',
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: false,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '5',
    title: 'Beachvolleyball-Turnier',
    slug: 'beachvolleyball-2025-07-12',
    description:
      'Offenes Beachvolleyball-Turnier am Lankensee. Anmeldung für Teams (4 Personen) bis zum 1. Juli. Teilnahmegebühr: 20€ pro Team.',
    description_en: null,
    location_name: 'Strandbad Lankensee',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-07-12',
    start_time: '10:00',
    end_date: null,
    end_time: null,
    is_all_day: false,
    category: 'sports',
    event_type: 'single',
    organizer_name: 'SV Zernsdorf',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: null,
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: true,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '6',
    title: 'Ortsbeiratssitzung',
    slug: 'ortsbeiratssitzung-2025-02-15',
    description:
      'Öffentliche Sitzung des Ortsbeirats Zernsdorf. Tagesordnung: Haushalt 2025, Spielplatzplanung, Verkehrssituation Hauptstraße.',
    description_en: null,
    location_name: 'Bürgerhaus Zernsdorf',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-02-15',
    start_time: '18:00',
    end_date: null,
    end_time: null,
    is_all_day: false,
    category: 'official',
    event_type: 'single',
    organizer_name: 'Ortsbeirat Zernsdorf',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: null,
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: false,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '7',
    title: 'Weihnachtsmarkt Zernsdorf',
    slug: 'weihnachtsmarkt-2025-12-06',
    description:
      'Gemütlicher Weihnachtsmarkt mit Glühwein, Waffeln, Kunsthandwerk und Weihnachtsprogramm für Kinder.',
    description_en: null,
    location_name: 'Dorfaue Zernsdorf',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-12-06',
    start_time: '14:00',
    end_date: '2025-12-06',
    end_time: '20:00',
    is_all_day: false,
    category: 'market',
    event_type: 'single',
    organizer_name: 'Bürgerhaus Zernsdorf',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: null,
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: false,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: '8',
    title: 'Lankensee-Schwimmen',
    slug: 'lankensee-schwimmen-2025-08-16',
    description:
      'Traditionelles Freiwasserschwimmen über 1,5 km im Lankensee. Anmeldung erforderlich. Für geübte Schwimmer ab 16 Jahren.',
    description_en: null,
    location_name: 'Strandbad Lankensee',
    location_address: null,
    location_business_id: null,
    latitude: null,
    longitude: null,
    start_date: '2025-08-16',
    start_time: '09:00',
    end_date: null,
    end_time: null,
    is_all_day: false,
    category: 'sports',
    event_type: 'single',
    organizer_name: 'DLRG Ortsgruppe Königs Wusterhausen',
    organizer_id: null,
    organizer_business_id: null,
    group_id: null,
    contact_email: null,
    contact_phone: null,
    website: null,
    image_url: null,
    images: null,
    is_active: true,
    is_featured: false,
    is_recurring: false,
    recurrence_rule: null,
    recurrence_end_date: null,
    requires_registration: true,
    max_participants: null,
    registration_url: null,
    created_by: null,
    updated_by: null,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];

export function getUpcomingEvents(): Event[] {
  const now = new Date();
  return MOCK_EVENTS
    .filter((e) => new Date(e.start_date) >= now)
    .sort((a, b) => new Date(a.start_date).getTime() - new Date(b.start_date).getTime());
}

export function getPastEvents(): Event[] {
  const now = new Date();
  return MOCK_EVENTS
    .filter((e) => new Date(e.start_date) < now)
    .sort((a, b) => new Date(b.start_date).getTime() - new Date(a.start_date).getTime());
}

export function getEventsByCategory(category: EventCategory): Event[] {
  return MOCK_EVENTS.filter((e) => e.category === category);
}

export function getAllEvents(): Event[] {
  return MOCK_EVENTS;
}
